[build]
  functions = "./netlify/functions"  # Path to your serverless functions
  command = "echo 'No build command'"
  publish = "public"  # Directory where your static files are located
  
[build.environment]
  # Specify the Python version
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"  # Assuming 'index' is your main function
  status = 20
